# Generated by Django 4.2 on 2025-01-05 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_category_todolist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
