# Generated by Django 4.2 on 2025-01-12 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_token_refresh',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
