# Generated by Django 5.1.4 on 2025-01-14 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('category', models.CharField(choices=[('GROCERIES', 'Groceries'), ('LEISURE', 'Leisure'), ('ELECTRONICS', 'Electronics'), ('UTILITIES', 'Utilities'), ('CLOTHING', 'Clothing'), ('HEALTH', 'Health'), ('OTHERS', 'Others')], default='OTHER', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['pk'],
            },
        ),
    ]
